// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABshG_UHFVq_0XvYnwkMEOP76dNS6HU10',
    appId: '1:455785112887:web:677fb3bec6f4821afe66b2',
    messagingSenderId: '455785112887',
    projectId: 'lesson66-eeb37',
    authDomain: 'lesson66-eeb37.firebaseapp.com',
    storageBucket: 'lesson66-eeb37.appspot.com',
    measurementId: 'G-JFXG6R0SBM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjAlM0cHhJXdRCWdX5bAbGJ14F_PxsN-Y',
    appId: '1:455785112887:android:12b1054a269bc9effe66b2',
    messagingSenderId: '455785112887',
    projectId: 'lesson66-eeb37',
    storageBucket: 'lesson66-eeb37.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAkI4E8eIGnMAU7znd1JCN76t-0wq2yMs',
    appId: '1:455785112887:ios:de27394cc8c72f3cfe66b2',
    messagingSenderId: '455785112887',
    projectId: 'lesson66-eeb37',
    storageBucket: 'lesson66-eeb37.appspot.com',
    iosBundleId: 'com.example.lesson65',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAkI4E8eIGnMAU7znd1JCN76t-0wq2yMs',
    appId: '1:455785112887:ios:de27394cc8c72f3cfe66b2',
    messagingSenderId: '455785112887',
    projectId: 'lesson66-eeb37',
    storageBucket: 'lesson66-eeb37.appspot.com',
    iosBundleId: 'com.example.lesson65',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABshG_UHFVq_0XvYnwkMEOP76dNS6HU10',
    appId: '1:455785112887:web:0aebfb6edc3f067dfe66b2',
    messagingSenderId: '455785112887',
    projectId: 'lesson66-eeb37',
    authDomain: 'lesson66-eeb37.firebaseapp.com',
    storageBucket: 'lesson66-eeb37.appspot.com',
    measurementId: 'G-4HWTLW96TW',
  );
}
